"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schema for the MOD FAIRsFAIR SemanticArtefactDistribution Profile'
$defs:
    mod:SemanticArtefactDistribution:
        allOf:
            - type: object
              properties:
                dcat:accessURL:
                    type: string
                    format: URI
                dcat:byteSize:
                    type: string
                dcat:downloadURL:
                    type: string
                    format: URI
                dct:accessRights:
                    type: string
                dct:description:
                    type: string
                dct:modified:
                    type: string
                dct:title:
                    type: string
                mod:authorProperty:
                    type: string
                mod:definitionProperty:
                    type: string
                mod:hasRepresentationLanguage:
                    type: string
                mod:hasSyntax:
                    type: string
                mod:hierarchyProperty:
                    type: string
                mod:metrics:
                    type: string
                mod:obsoleteParent:
                    type: string
                mod:obsoleteProperty:
                    type: string
                mod:prefLabelProperty:
                    type: string
                mod:sampleQueries:
                    type: string
                mod:synonymProperty:
                    type: string

anyOf:
  - $ref: "#/$defs/mod:SemanticArtefactDistribution"
